name: Mac

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  CMake-Mac:
    runs-on: macos-13

    env:
      CMAKE_BUILD_DIR: build
      VCPKG_ROOT: ${{github.workspace}}/vcpkg

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch Vcpkg commits
        working-directory: vcpkg
        run: git fetch --depth=10
      - name: Install local vcpkg
        working-directory: vcpkg
        run: ./bootstrap-vcpkg.sh
      - uses: lukka/get-cmake@latest
      - name: CMake configure
        run: |
          cmake -S . -B ${{env.CMAKE_BUILD_DIR}} -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: CMake build
        run: |
          cmake --build ${{env.CMAKE_BUILD_DIR}} --config Release
