name: Windows

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  CMake-Windows:
    runs-on: windows-2022

    env:
      CMAKE_BUILD_DIR: build
      VCPKG_ROOT: ${{github.workspace}}/vcpkg

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch Vcpkg commits
        working-directory: vcpkg
        run: git fetch --unshallow
      - name: Install local vcpkg
        working-directory: vcpkg
        run: ./bootstrap-vcpkg.sh
      # Install latest CMake.
      - uses: lukka/get-cmake@latest
      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v6
        with:
          path: |
            ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          key: |
            ${{ hashFiles( 'vcpkg_manifest/vcpkg.json', '.git/modules/vcpkg/HEAD' )}}-win-invalidate
      - name: CMake configure
        run: |
          cmake -S . -B ${{env.CMAKE_BUILD_DIR}} -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: CMake build
        run: |
          cmake --build ${{env.CMAKE_BUILD_DIR}} --config Release
